'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Partial Public Class acc_Pay_Extensions
    Public Property ID As Integer
    Public Property Pay_Code As String
    Public Property Pay_Type As String
    Public Property Pay_Title As String
    Public Property Pay_Name As String
    Public Property Pay_Description As String
    Public Property Notes As String
    Public Property Added_By As String
    Public Property Added_Date As Nullable(Of Date)
    Public Property Modified_By As String
    Public Property Modified_Date As Nullable(Of Date)

End Class
