'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Partial Public Class acc_Employees
    Public Property ID As Integer
    Public Property Employee_Code As String
    Public Property Employee_ID As String
    Public Property Employee_Name As String
    Public Property Employee_Address As String
    Public Property Employee_Contact As String
    Public Property Employee_Date_Birth As Nullable(Of Date)
    Public Property Employee_Age As Nullable(Of Integer)
    Public Property Employee_Birth_Place As String
    Public Property Employee_Civil_Status As String
    Public Property Employee_Corporation As String
    Public Property Employee_Branch As String
    Public Property Employee_Department As String
    Public Property Employee_Position As String
    Public Property Employee_Pay_Level As String
    Public Property Employee_Pay_Class As String
    Public Property Employee_Status As String
    Public Property Employee_Date_Hired As Nullable(Of Date)
    Public Property Employee_Date_Probationary As Nullable(Of Date)
    Public Property Employee_Date_Regular As Nullable(Of Date)
    Public Property Employee_Service_Length As String
    Public Property Employee_TIN As String
    Public Property Employee_SSS As String
    Public Property Employee_PHIC As String
    Public Property Employee_PAG_IBIG As String
    Public Property Employee_Attainment As String
    Public Property Employee_Course As String
    Public Property Employee_Name_Spouse As String
    Public Property Employee_Children As String
    Public Property Employee_Driver_License As String
    Public Property Employee_Driver_License_Expiry As Nullable(Of Date)
    Public Property Notes As String
    Public Property Added_By As String
    Public Property Added_Date As Nullable(Of Date)
    Public Property Modified_By As String
    Public Property Modified_Date As Nullable(Of Date)

End Class
