'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Partial Public Class acc_Chart_Of_Accounts
    Public Property ID As Integer
    Public Property COA_Code As String
    Public Property COA_Statement As String
    Public Property COA_Level As Integer
    Public Property COA_Type As String
    Public Property COA_Summary As String
    Public Property COA_Name As String
    Public Property COA_Desc As String
    Public Property COA_Normal As String
    Public Property Notes As String
    Public Property Added_By As String
    Public Property Added_Date As Nullable(Of Date)
    Public Property Modified_By As String
    Public Property Modified_Date As Nullable(Of Date)
    Public Property Corporation As String
    Public Property IsLocked As Nullable(Of Boolean)
    Public Property Locked_By As String
    Public Property Locked_Date As Nullable(Of Date)
    Public Property IsFS As Nullable(Of Boolean)
    Public Property IsLedger As Nullable(Of Boolean)
    Public Property Balance As Nullable(Of Decimal)
    Public Property Balance_Date As Nullable(Of Date)
    Public Property Balance_Limit As Nullable(Of Decimal)
    Public Property Balance_Running As Nullable(Of Decimal)

End Class
