'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Partial Public Class acc_Checks
    Public Property ID As Integer
    Public Property Check_Code As String
    Public Property Check_Number As String
    Public Property Bank_Account As String
    Public Property Check_Payee As String
    Public Property Check_Amount As Nullable(Of Decimal)
    Public Property Check_Amount_Words As String
    Public Property Issued_Date As Nullable(Of Date)
    Public Property IsCancelled As Nullable(Of Boolean)
    Public Property Check_Description As String
    Public Property Notes As String
    Public Property Added_By As String
    Public Property Added_Date As Date
    Public Property Modified_By As String
    Public Property Modified_Date As Nullable(Of Date)
    Public Property IsIssued As Nullable(Of Boolean)
    Public Property Reference As String
    Public Property IsLocked As Nullable(Of Boolean)
    Public Property Locked_By As String
    Public Property Locked_Date As Nullable(Of Date)

End Class
