'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Partial Public Class acc_Banks
    Public Property ID As Integer
    Public Property Bank_Code As String
    Public Property Bank_Account As String
    Public Property Account_Name As String
    Public Property Bank_Name As String
    Public Property Bank_BRSTN As String
    Public Property Bank_Manager As String
    Public Property Bank_Address As String
    Public Property Bank_Tel_Number As String
    Public Property Bank_Description As String
    Public Property Notes As String
    Public Property Added_By As String
    Public Property Added_Date As Date
    Public Property Modified_By As String
    Public Property Modified_Date As Nullable(Of Date)
    Public Property Corporation As String
    Public Property COA_Code As String

End Class
