'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Partial Public Class acc_Account_Names
    Public Property ID As Integer
    Public Property Account_Code As String
    Public Property Account_Type As String
    Public Property Account_Name As String
    Public Property Account_Address As String
    Public Property Account_Mobile As String
    Public Property Account_Description As String
    Public Property Notes As String
    Public Property Added_By As String
    Public Property Added_Date As Date
    Public Property Modified_By As String
    Public Property Modified_Date As Nullable(Of Date)

End Class
