'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AccEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New(MyClassLibrary.Classes.class_Database.connectionStringAccEntity)
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property acc_Banks() As DbSet(Of acc_Banks)
    Public Overridable Property acc_Checks() As DbSet(Of acc_Checks)
    Public Overridable Property acc_Journal_Profiles() As DbSet(Of acc_Journal_Profiles)
    Public Overridable Property acc_Chart_Of_Accounts() As DbSet(Of acc_Chart_Of_Accounts)
    Public Overridable Property acc_Account_Names() As DbSet(Of acc_Account_Names)
    Public Overridable Property view_Checks() As DbSet(Of view_Checks)
    Public Overridable Property view_Journal_Profiles() As DbSet(Of view_Journal_Profiles)

End Class
