'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Partial Public Class view_Journal_Profiles
    Public Property ID As Integer
    Public Property Journal_Type As String
    Public Property Profile_Name As String
    Public Property Profile_Description As String
    Public Property Balance_Type As String
    Public Property Notes As String
    Public Property Added_By As String
    Public Property Added_Date As Nullable(Of Date)
    Public Property Modified_By As String
    Public Property Modified_Date As Nullable(Of Date)
    Public Property Profile_Code As String
    Public Property Payment_Code As String
    Public Property Profile_VAT As Nullable(Of Boolean)
    Public Property Profile_Corporation As String
    Public Property Custom_COA As Nullable(Of Boolean)
    Public Property Profile_Type As String
    Public Property Friendly_Name As String
    Public Property COA_Code As String
    Public Property COA_Name As String

End Class
